const config = {
  rates: {
    hashtag: 0.03,
    author: 0.05,
    linkHost: 0.1,
    hasLink: 0.01,
    hasImage: 0.001,
    retweet_count: 2,
    favorite_count: 1.3
  },
  ignoredLinkHosts: [
    /twitter.com/,
    /buff.ly/,
    /dlvr.it/,
    /bit.do/,
    /t.co/,
    /lnkd.in/,
    /db.tt/,
    /qr.ae/,
    /adf.ly/,
    /goo.gl/,
    /bitly.com/,
    /cur.lv/,
    /tinyurl.com/,
    /ow.ly/,
    /bit.ly/,
    /adcrun.ch/,
    /ity.im/,
    /q.gs/,
    /viralurl.com/,
    /is.gd/,
    /vur.me/,
    /bc.vc/,
    /twitthis.com/,
    /u.to/,
    /j.mp/,
    /buzurl.com/,
    /cutt.us/,
    /u.bb/,
    /yourls.org/,
    /crisco.com/,
    /x.co/,
    /prettylinkpro.com/,
    /viralurl.biz/,
    /adcraft.co/,
    /virl.ws/,
    /scrnch.me/,
    /filoops.info/,
    /vurl.bz/,
    /vzturl.com/,
    /lemde.fr/,
    /qr.net/,
    /1url.com/,
    /tweez.me/,
    /7vd.cn/,
    /v.gd/,
    /dft.ba/,
    /tr.im/,
    /tinyarrows.com/
  ]
};

export default config;
